### ISSUE TITLE
Tailwind Variants: a possible replacement for cva + tailwind-merge

### ISSUE THREAD

**Issue by jvzaniolo** [kobaltedev/pigment#2]
Hi Fabien,

This is not a feature request, I just wanted to share with you this library I'm using to build my company's design system with Radix UI and Tailwind CSS which has similar structure with this project.
Maybe it can be useful to you :)

https://www.tailwind-variants.org/

It was built by the creators of [NextUI](https://nextui.org/), another similar component library using React Aria and Tailwind CSS (in its wip v2.0)

**Comment by apollo79** [comment]
If you are interested in using `tailwind-variants`, I could open a PR

**Comment by fabien-ml** [comment]
Hi, thank you for mentioning this library. The DX is way better when dealing with slots + built-in tailwind-merge. 👍
